import french_converter

tests = {
    'p/artem': 'p/aʁ',
    'b/assum': 'b/a',
    'm/are': 'm/ɛʁ',
    'am/a:tum': 'am/e', # Officially /ɛme/ due to assimilation with other verb forms.
    'f/a:gum': 'f/u',
    'b/awan': 'b/u',
    'mediet/a:tem': 'mwadj/e', # Officially /mwatje/, likely due to vowel loss before lenition.
    'k/a:rum': 'ʃ/ɛʁ',
    's/eptem': 's/e', # Officially /sɛt/. Numbers tend to be more resistant to evolution.
    'h/eri': 'j/ɛʁ',
    'p/edem': 'pj/e',
    's/ikkum': 's/ɛk',
    'p/e:ram': 'pw/aʁ',
    'vid/e:re': 'vw/aʁ',
    'k/e:ram': 's/iʁ',
    'merk/e:dem': 'mɛʁs/i',
    'v/i:tam': 'v/i',
    'v/i:llam': 'v/il',
    'p/ortam': 'p/ɔʁt',
    's/ottum': 's/o',
    's/ottam': 's/ɔt',
    'gr/ossum': 'gʁ/o',
    'gr/ossam': 'gʁ/os',
    'n/ovum': 'n/œf',
    'k/orem': 'k/œʁ',
    's/ubtus': 's/u', # The final result is correct, but the steps aren't entirely correct due to the /b/ assimilating with the /t/.
    's/urdum': 's/uʁ',
    'n/o:dum': 'n/ø',
    'd/u:rum': 'd/yʁ',
    'n/u:llam': 'n/yl',
    '/awrum': '/ɔʁ',
    'k/awsam': 'ʃ/oz',
    'tr/awkon': 'tʁ/u',
    '/annum': '/ɑ~',
    'k/antum': 'ʃ/ɑ~',
    's/a:num': 's/ɛn',
    '/amat': '/ɛm',
    's/a:num': 's/ɛ~',
    'f/amem': 'f/ɛ~',
    'k/anem': 'ʃj/ɛ~',
    'd/entem': 'd/ɑ~',
    't/enent': 'tj/ɛ~', # Officially /tjɛn/, but I think this is due to the resulting /nnt/ cluster that occurs after the loss of the posttonic vowel. I doubt this cluster is valid, so there should probably be a /ə/ inserted in there somewhere which causes the stressed vowel to remain open. This is further backed by the table of vowel outcomes indicating that it's supposed to be open. This might be corrected if I can work out how to deal with consonant clusters.
    'b/ene': 'bj/ɛ~',
    't/enet': 'tj/ɛ~',
    'l/ingwa': 'l/ɑ~g',
    'p/e:nam': 'p/ɛn',
    'pl/e:num': 'pl/ɛ~',
    's/inum': 's/ɛ~',
    'rak/e:mum': 'ʁɛz/ɛ~',
    'kw/i:nkwe': 's/ɛ~k',
    'f/i:num': 'f/ɛ~',
    'f/i:nam': 'f/in',
    'p/ontem': 'p/ɔ~',
    'b/onam': 'b/ɔn',
    'k/omes': 'k/ɔ~',
    'd/o:num': 'd/ɔ~',
    'd/o:nat': 'd/ɔn',
    '/u:num': '/ɛ~',
    'perf/u:mum': 'pɛʁf/ɛ~', # Officially /paʁfɛ~/. /e/ occasionally becomes /a/ before /r/ when pretonic.
    '/u:nam': '/yn',
    'pl/u:mam': 'pl/ym',
    'b/assum': 'b/a',
    'f/estam': 'f/ɛt',
    'b/estiam': 'b/ɛs', # Officially /bɛt/. According to Wiktionary, this might've come from Vulgar Latin <be:sta>, which would actually give the expected result. I suspect this is probably the case.
    'ab/i:ssimum': 'av/im', # Officially /abim/. According to Wiktionary, this was borrowed Late Latin, so it was probably borrowed sometime after the second lenition, which would have turned the /b/ into /v/. However, the posttonic vowel loss, which resulted in the loss of the second /i/, supposedly occurred before the second lenition, so I'm not entirely sure what happened here. It could also could have been influenced the Latin word, something which happened occasionally.
    'k/ostam': 'k/ot',
    'k/o:nstat': 'k/ut',
    'f/u:stem': 'f/y',
    'f/alsum': 'f/o',
    'p/almam': 'p/om',
    'b/ellum': 'b/o',
    'b/ellam': 'b/ɛl',
    '/akwa': '/o',
    'm/elius': 'mj/ø',
    'kap/illum': 'ʃav/ø', # Officially /ʃəvø/. Pretonic /a/ occasionally reduces to /ə/.
    'f/iltrum': 'f/øtʁ',
    'gent/i:lem': 'ʒɑ~t/i',
    'f/ollem': 'f/u',
    'f/ollam': 'f/ɔl',
    'k/olpum': 'k/u',
    '/uolet': 'v/ø',
    '/okulus': 'j/ø',
    'p/ulsat': 'p/us',
    'k/u:lum': 'k/y',
    'f/aktum': 'f/ɛ',
    'pal/a:tium': 'pal/ɛ',
    'pl/a:gam': 'pl/ɛ',
    'pl/aket': 'pl/ɛ',
    'p/aria': 'p/jaʁ', # Officially /pɛʁ/ because the /j/ didn't metathesize. I'm not sure why.
    '/iaket': 'ʒ/i',
    'k/akat': 'ʃ/i',
    'l/ektum': 'l/i',
    's/eks': 's/i', # Officially /sis/. Again, umbers tend to be more resistant to evolution.
    'p/ejor': 'p/iʁ',
    't/e:ktum': 'tw/a',
    'r/e:gem': 'ʁw/a',
    'n/igrum': 'nw/aʁ',
    'f/e:riam': 'fw/aʁ',
    'n/oktem': 'nɥ/i',
    'h/odie': 'ɥ/i',
    'k/oksam': 'kɥ/is',
    'b/uksitam': 'bw/ad', # Officially /bwat/, liekly due to vowel loss before lenition.
    'kr/uken': 'kʁw/a',
    'fr/u:ktum': 'fʁɥ/i',
    'g/awdia': 'ʒw/a',
    'b/aneum': 'b/ɛ~',
    's/anktum': 's/ɛ~',
    'mont/a:neam': 'mɔ~t/aɲ',
    'p/inktum': 'p/ɛ~',
    'ins/igniam': 'ez/ɛɲ', # Officially /ɑ~sɛɲ/ due to it being borrowed after the /ns/ > /s/ change.
    'l/i:neam': 'l/iɲ',
    'l/onge': 'lw/ɛ~',
    'fr/ogna': 'fʁ/ɔɲ',
    'p/unktum': 'pw/ɛ~',
    'k/uneum': 'kw/ɛ~',
    'werek/undiam': 'vɛʁg/ɔɲ',
    'i/u:nium': 'ʒɥ/ɛ~',
    'sek/u:rum': 's/yʁ',
    'lu:k/o:rem': 'lɥ/œʁ',
    'am/i:kum': 'am/i',
    'ag/ustum': 'a/u',
    'f/okum': 'f/ø',
}

if __name__ == '__main__':
    for k, v in tests.items():
        if (result := french_converter.evolve(k)) != v:
            print(f'Error evolving {k} - expected {v} but got {result}')
    # print(french_converter.evolve('sek/u:rum', True))
